# Generated by Django 2.2.7 on 2019-11-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('sensor_type', models.CharField(max_length=250)),
                ('date', models.DateField(blank=True)),
                ('time', models.TimeField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('lng', models.FloatField(blank=True)),
                ('measurement_value', models.FloatField(blank=True)),
            ],
        ),
    ]
