# Generated by Django 2.2.6 on 2019-10-29 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protectedobject',
            name='detour_paths',
        ),
        migrations.RemoveField(
            model_name='protectedobject',
            name='robots',
        ),
        migrations.AddField(
            model_name='detourpath',
            name='detour_paths',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detour_paths', to='api.ProtectedObject'),
        ),
        migrations.AddField(
            model_name='robot',
            name='robots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='api.ProtectedObject'),
        ),
    ]
