# Generated by Django 2.2.6 on 2019-10-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191029_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detourpath',
            old_name='detour_paths',
            new_name='protectedobject',
        ),
        migrations.RenameField(
            model_name='robot',
            old_name='robots',
            new_name='protectedobject',
        ),
    ]
